name: Release

on:
  push:
    tags:
      - v*

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: yarn install
      - run: yarn compile
      # Compile the schema and package the extension
      - run: docker run --rm -v "${GITHUB_WORKSPACE}:/github" ubuntu:rolling /bin/sh -c 'apt-get update -qq > /dev/null && DEBIAN_FRONTEND=noninteractive apt-get install -qq -y gnome-shell yarnpkg > /dev/null && cd /github && yarnpkg package'
      - name: Upload package to Github
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: vscode-search-provider@jomik.org.shell-extension.zip
          asset_name: vscode-search-provider@jomik.org.shell-extension.zip
          tag: ${{ github.ref }}
          overwrite: true
